# Generated by Django 4.2.1 on 2023-06-01 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='* 책 제목은 정확하게 기입해주세요.', max_length=200, verbose_name='책 이름')),
                ('author', models.CharField(max_length=100, verbose_name='저자')),
                ('publisher', models.CharField(max_length=100, verbose_name='출판사')),
                ('price', models.IntegerField(verbose_name='정가')),
                ('content', models.TextField(verbose_name='상품 설명')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='등록(수정)일')),
                ('under_line', models.BooleanField(verbose_name='밑줄 유무')),
                ('written', models.BooleanField(verbose_name='필기 유무')),
                ('page_named', models.BooleanField(verbose_name='이름 기입')),
                ('page_age', models.BooleanField(verbose_name='페이지 변색')),
                ('ripped', models.BooleanField(verbose_name='페이지 훼손')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
