# Generated by Django 4.2.1 on 2023-05-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='* 책 제목은 정확하게 기입해주세요.', max_length=200, verbose_name='책 이름')),
                ('author', models.CharField(max_length=100, verbose_name='글쓴이')),
                ('price', models.IntegerField(verbose_name='상품 가격')),
                ('content', models.TextField(verbose_name='상품 설명')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='등록(수정)일')),
            ],
        ),
    ]
