# Generated by Django 4.2.1 on 2023-05-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanbatMarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='page_age',
            field=models.BooleanField(default=False, verbose_name='페이지 변색'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='page_named',
            field=models.BooleanField(default=False, verbose_name='이름 기입'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='ripped',
            field=models.BooleanField(default=False, verbose_name='페이지 훼손'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='under_line',
            field=models.BooleanField(default=False, verbose_name='밑줄 유무'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='written',
            field=models.BooleanField(default=False, verbose_name='필기 유무'),
            preserve_default=False,
        ),
    ]
