# Generated by Django 4.2.1 on 2023-05-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HanbatMarket', '0002_board_page_age_board_page_named_board_ripped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='publisher',
            field=models.CharField(default=False, max_length=100, verbose_name='출판사'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='seller',
            field=models.CharField(default=False, max_length=100, verbose_name='판매자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.CharField(max_length=100, verbose_name='저자'),
        ),
        migrations.AlterField(
            model_name='board',
            name='price',
            field=models.IntegerField(verbose_name='정가'),
        ),
    ]
